apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: cassieluoliazurevotingappredis 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cassieluoliazurevotingappredis 
    spec:
      containers:
        - name: cassieluoliazurevotingappredis 
          image: hellocontainerregistry.azurecr.io/cassieluoliazurevotingappredis
          ports:
          - containerPort: 80